set_property IOSTANDARD LVCMOS33 [get_ports *]

## Clock signal
set_property PACKAGE_PIN W5 [get_ports clock]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clock]

#set_property PACKAGE_PIN A16 [get_ports io_slowClock]

## LED and reset button
set_property PACKAGE_PIN U16 [get_ports {io_led}]
set_property PACKAGE_PIN T17 [get_ports reset]
set_property PACKAGE_PIN B18 [get_ports {io_rx}]
set_property PACKAGE_PIN A18 [get_ports {io_tx}]

set_property PACKAGE_PIN E19 [get_ports {io_pc[0]}]
set_property PACKAGE_PIN U19 [get_ports {io_pc[1]}]
set_property PACKAGE_PIN V19 [get_ports {io_pc[2]}]
set_property PACKAGE_PIN W18 [get_ports {io_pc[3]}]
set_property PACKAGE_PIN U15 [get_ports {io_pc[4]}]
set_property PACKAGE_PIN U14 [get_ports {io_pc[5]}]
set_property PACKAGE_PIN V14 [get_ports {io_pc[6]}]
set_property PACKAGE_PIN V13 [get_ports {io_pc[7]}]
set_property PACKAGE_PIN V3  [get_ports {io_pc[8]}]
set_property PACKAGE_PIN W3  [get_ports {io_pc[9]}]
set_property PACKAGE_PIN U3  [get_ports {io_pc[10]}]
set_property PACKAGE_PIN P3  [get_ports {io_pc[11]}]
set_property PACKAGE_PIN N3  [get_ports {io_pc[12]}]
set_property PACKAGE_PIN P1  [get_ports {io_pc[13]}]
set_property PACKAGE_PIN L1  [get_ports {io_pc[14]}]

set_property PACKAGE_PIN W7 [get_ports {io_seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {io_seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {io_seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {io_seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {io_seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {io_seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {io_seg[6]}]
#set_property PACKAGE_PIN V7 [get_ports {dp}]
set_property PACKAGE_PIN U2 [get_ports {io_an[0]}]
set_property PACKAGE_PIN U4 [get_ports {io_an[1]}]
set_property PACKAGE_PIN V4 [get_ports {io_an[2]}]
set_property PACKAGE_PIN W4 [get_ports {io_an[3]}]