set_location_assignment PIN_Y2 -to clock
set_location_assignment PIN_G19 -to io_led
set_location_assignment PIN_AB28 -to reset
set_location_assignment PIN_F19 -to io_pc[0]
set_location_assignment PIN_E19 -to io_pc[1]
set_location_assignment PIN_F21 -to io_pc[2]
set_location_assignment PIN_F18 -to io_pc[3]
set_location_assignment PIN_E18 -to io_pc[4]
set_location_assignment PIN_J19 -to io_pc[5]
set_location_assignment PIN_H19 -to io_pc[6]
set_location_assignment PIN_J17 -to io_pc[7]
set_location_assignment PIN_G17 -to io_pc[8]
set_location_assignment PIN_J15 -to io_pc[9]

set_location_assignment PIN_G12 -to io_rx
set_location_assignment PIN_G9 -to io_tx
set_location_assignment PIN_G14 -to io_cts
set_location_assignment PIN_M23 -to io_button

set_location_assignment PIN_AB7 -to io_sram_address[0]
set_location_assignment PIN_AD7 -to io_sram_address[1]
set_location_assignment PIN_AE7 -to io_sram_address[2]
set_location_assignment PIN_AC7 -to io_sram_address[3]
set_location_assignment PIN_AB6 -to io_sram_address[4]
set_location_assignment PIN_AE6 -to io_sram_address[5]
set_location_assignment PIN_AB5 -to io_sram_address[6]
set_location_assignment PIN_AC5 -to io_sram_address[7]
set_location_assignment PIN_AF5 -to io_sram_address[8]
set_location_assignment PIN_T7 -to io_sram_address[9]
set_location_assignment PIN_AF2 -to io_sram_address[10]
set_location_assignment PIN_AD3 -to io_sram_address[11]
set_location_assignment PIN_AB4 -to io_sram_address[12]
set_location_assignment PIN_AC3 -to io_sram_address[13]
set_location_assignment PIN_AA4 -to io_sram_address[14]
set_location_assignment PIN_AB11 -to io_sram_address[15]
set_location_assignment PIN_AC11 -to io_sram_address[16]
set_location_assignment PIN_AB9 -to io_sram_address[17]
set_location_assignment PIN_AB8 -to io_sram_address[18]
set_location_assignment PIN_T8 -to io_sram_address[19]

set_location_assignment PIN_AH3 -to io_sram_data[0]
set_location_assignment PIN_AF4 -to io_sram_data[1]
set_location_assignment PIN_AG4 -to io_sram_data[2]
set_location_assignment PIN_AH4 -to io_sram_data[3]
set_location_assignment PIN_AF6 -to io_sram_data[4]
set_location_assignment PIN_AG6 -to io_sram_data[5]
set_location_assignment PIN_AH6 -to io_sram_data[6]
set_location_assignment PIN_AF7 -to io_sram_data[7]
set_location_assignment PIN_AD1 -to io_sram_data[8]
set_location_assignment PIN_AD2 -to io_sram_data[9]
set_location_assignment PIN_AE2 -to io_sram_data[10]
set_location_assignment PIN_AE1 -to io_sram_data[11]
set_location_assignment PIN_AE3 -to io_sram_data[12]
set_location_assignment PIN_AE4 -to io_sram_data[13]
set_location_assignment PIN_AF3 -to io_sram_data[14]
set_location_assignment PIN_AG3 -to io_sram_data[15]

set_location_assignment PIN_AD5 -to io_sram_outputEnable
set_location_assignment PIN_AE8 -to io_sram_writeEnable
set_location_assignment PIN_AF8 -to io_sram_chipSelect
set_location_assignment PIN_AD4 -to io_sram_strobe_0
set_location_assignment PIN_AC4 -to io_sram_strobe_1